### ISSUE TITLE
changelog got removed

### ISSUE THREAD

**Issue by bastelfreak** [ruby/ruby2_keywords#17]
Hi,
it looks like the changelog got removed with the latest 0.0.5 release. Now there is a rake task to generate it on the fly. Is there a reason why you don't keep it in the  repos / is it documented somehwere else?  I think it's quite helpful to me as a user to read a changelog before I upgrade a gem. Also I'm packaging this gem for Arch Linux and I would like to vendor the changelog file into the package.

Also the gemspec references a ChangeLog and a /logs/ChangeLog file but both aren't available.

**Comment by hsbt** [comment]
👋  I created releases with changes. see https://github.com/ruby/ruby2_keywords/releases
