### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by pvalena** [ruby/ruby2_keywords#4]
and ship it in a `.gem` file. We need to point to an actual license file in Fedora. Also on `rubygems.org` the license is `Ruby`, but in `README.md` the you're pointing to `2-Clause BSD License.`.

**Comment by pvalena** [comment]
_Note: I do not want to be pedantic or anything :), it's just that I get confused a bit, even though the license is basically the same, it doesn't need to be, so it'd be nice to have an actual file to point to._

Thanks!

**Comment by terceiro** [comment]
hello

I am looking into providing this in Debian, and I have the same concerns.
