### ISSUE TITLE
Request for additional documentation

### ISSUE THREAD

**Issue by brian-kephart** [ruby/ruby2_keywords#6]
It's unclear how this gem can be applied to alternative approaches to method definition. For example, can `ruby2_keywords` be applied to the following code?

```ruby
def self.define_proxy(name)
  define_method name do |*args, &block|
    view_context.send(name, *args, &block)
  end
end
```

(Code example is from [Draper](https://github.com/drapergem/draper/pull/885))

**Comment by mame** [comment]
Thank you for contacting us. I think the following is enough like a normal `def` definition.

```ruby
def self.define_proxy(name)
  define_method name do |*args, &block|
    view_context.send(name, *args, &block)
  end
  ruby2_keywords name
end
```

Do you have any problem about this? I'll be happy to add this to the README.md.

**Comment by brian-kephart** [comment]
Thank you very much! Your suggestion works well, and I think it would be a good addition to the README.
